name: Generate snake animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate light theme snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: 2bitdevv
          outputs: dist/github-snake.svg

      - name: Generate dark theme snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: 2bitdevv
          outputs: dist/github-snake-dark.svg
          palette: github-dark


      - name: Commit and push to output branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout --orphan output
          mkdir -p dist
          git add dist/github-snake.svg dist/github-snake-dark.svg
          git commit -m "Generate light and dark theme snake svg"
          git push -f origin output
